# Generated by Django 5.2.4 on 2025-07-07 20:31

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_name", models.CharField(max_length=200, verbose_name="Название продукта")),
                ("model", models.CharField(max_length=200, verbose_name="Модель продукта")),
                ("release_date", models.DateField(verbose_name="Дата выхода на рынок")),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "unique_together": {("product_name", "model")},
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("supplier_name", models.CharField(max_length=200, verbose_name="Название поставщика")),
                (
                    "chain_type",
                    models.CharField(
                        choices=[
                            ("factory", "Завод"),
                            ("retail", "Розничная сеть"),
                            ("entrepreneur", "Индивидуальный предприниматель"),
                        ],
                        max_length=20,
                        verbose_name="Тип цепочки",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Email")),
                ("country", models.CharField(max_length=200, verbose_name="Страна")),
                ("city", models.CharField(max_length=200, verbose_name="Город")),
                ("street", models.CharField(max_length=200, verbose_name="Улица")),
                ("building_number", models.CharField(max_length=100, verbose_name="Номер дома")),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=20,
                        verbose_name="Задолженность перед поставщиком",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Время создания")),
                (
                    "products",
                    models.ManyToManyField(related_name="suppliers", to="chain.product", verbose_name="Продукты"),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clients",
                        to="chain.supplier",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поставщик",
                "verbose_name_plural": "Поставщики",
                "ordering": ["supplier_name"],
            },
        ),
    ]
